
name: mqe3
services:
  mqe3:
    build:
      context: .
      dockerfile: Dockerfile
    image: mqe3
    container_name: mqe
    working_dir: /mqe

    volumes:
      - ./core:/mqe/core
      - ./demo.py:/mqe/demo.py
      - ./pyproject.toml:/mqe/pyproject.toml
      - ./uv.lock:/mqe/uv.lock

    command: sleep infinity
