[project]
name = "mini-query-engine"
version = "0.1.7"
description = "Educational mini query engine in Python built on top of Apache Arrow, used to explore how query engines work under the hood."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyarrow>=22.0.0",
]
